#!/bin/bash

echo "🚀 Advanced PythonAnywhere Automation Setup"
echo "============================================="
echo ""

echo "📋 Method 1: Manual Git Pull (Recommended for beginners)"
echo "------------------------------------------------------"
echo "1. Set up Git repository (follow setup-git-deployment.sh)"
echo "2. For updates, run these commands in PythonAnywhere:"
echo "   cd stock-options-tracker"
echo "   git pull"
echo "   # Then reload web app"
echo ""

echo "📋 Method 2: Automated Webhook Deployment"
echo "------------------------------------------"
echo "This requires a paid PythonAnywhere account and more setup."
echo ""

echo "📋 Method 3: Scheduled Task (Free Tier)"
echo "---------------------------------------"
echo "Set up a scheduled task to pull updates every few minutes:"
echo ""
echo "1. Go to Tasks tab in PythonAnywhere"
echo "2. Click 'Add a new task'"
echo "3. Set command:"
echo "   cd /home/YOUR_USERNAME/stock-options-tracker && git pull"
echo "4. Set to run every 5 minutes"
echo "5. This will automatically pull updates"
echo ""

echo "📋 Method 4: Always-on Task (Paid Tier)"
echo "---------------------------------------"
echo "For paid accounts, you can set up a background task:"
echo ""
echo "1. Go to Tasks tab"
echo "2. Click 'Add a new task'"
echo "3. Set command:"
echo "   while true; do"
echo "     cd /home/YOUR_USERNAME/stock-options-tracker"
echo "     git pull"
echo "     sleep 60"
echo "   done"
echo "4. This runs continuously and pulls updates every minute"
echo ""

echo "📋 Method 5: GitHub Actions (Advanced)"
echo "--------------------------------------"
echo "Create .github/workflows/deploy.yml:"
echo ""
echo "name: Deploy to PythonAnywhere"
echo "on:"
echo "  push:"
echo "    branches: [ main ]"
echo "jobs:"
echo "  deploy:"
echo "    runs-on: ubuntu-latest"
echo "    steps:"
echo "    - name: Deploy to PythonAnywhere"
echo "      run: |"
echo "        ssh YOUR_USERNAME@ssh.pythonanywhere.com 'cd stock-options-tracker && git pull'"
echo ""

echo "🔧 Quick Setup Commands"
echo "-----------------------"
echo "Run these commands to set up your repository:"
echo ""
echo "# Check current status"
echo "git status"
echo ""
echo "# Add all files"
echo "git add ."
echo ""
echo "# Commit changes"
echo "git commit -m 'Initial commit - Stock Options Tracker'"
echo ""
echo "# Add remote (replace YOUR_USERNAME)"
echo "git remote add origin https://github.com/YOUR_USERNAME/stock-options-tracker.git"
echo ""
echo "# Push to GitHub"
echo "git push -u origin main"
echo ""

echo "✅ After Git Setup:"
echo "- Your code is backed up in GitHub"
echo "- Easy to update PythonAnywhere with 'git pull'"
echo "- Version control for all changes"
echo "- Can collaborate with others"
echo "- Rollback to previous versions if needed"
