#!/bin/bash

echo "🚀 Automated Git to PythonAnywhere Deployment Setup"
echo "==================================================="
echo ""

echo "✅ Your Stock Options Tracker is restored and ready!"
echo ""

echo "📋 Step 1: Push Current Code to GitHub"
echo "--------------------------------------"
echo "Your GitHub repository: https://github.com/PrometheusPrograms/stock-options-tracker"
echo ""
echo "Push your current code:"
echo "git add ."
echo "git commit -m 'Restore Stock Options Tracker with automated deployment'"
echo "git push origin main"
echo ""

echo "📋 Step 2: Set Up PythonAnywhere Automated Deployment"
echo "------------------------------------------------------"
echo ""
echo "Method 1: Scheduled Task (Free Tier - Recommended)"
echo "1. Go to PythonAnywhere → Tasks tab"
echo "2. Click 'Add a new task'"
echo "3. Set command:"
echo "   cd /home/YOUR_USERNAME/stock-options-tracker && git pull && touch /tmp/reload.txt"
echo "4. Set to run every 5 minutes"
echo "5. This automatically pulls updates from GitHub"
echo ""
echo "Method 2: Always-on Task (Paid Tier)"
echo "1. Go to Tasks tab"
echo "2. Add task with command:"
echo "   while true; do"
echo "     cd /home/YOUR_USERNAME/stock-options-tracker"
echo "     git pull"
echo "     sleep 60"
echo "   done"
echo "3. This runs continuously and pulls updates every minute"
echo ""
echo "Method 3: GitHub Actions (Advanced)"
echo "1. Create .github/workflows/deploy.yml"
echo "2. Set up SSH keys for PythonAnywhere"
echo "3. Automatic deployment on every push"
echo ""

echo "📋 Step 3: PythonAnywhere Initial Setup"
echo "---------------------------------------"
echo "1. Go to https://pythonanywhere.com"
echo "2. Sign up for free account"
echo "3. Files tab → Clone from Git"
echo "4. Enter: https://github.com/PrometheusPrograms/stock-options-tracker.git"
echo "5. Web tab → Add web app → Flask, Python 3.10"
echo "6. Source: /home/YOUR_USERNAME/stock-options-tracker"
echo "7. WSGI: wsgi.py"
echo ""

echo "📋 Step 4: Configure WSGI File"
echo "------------------------------"
echo "In Web tab, click WSGI file and replace with:"
echo ""
echo "import sys"
echo "path = '/home/YOUR_USERNAME/stock-options-tracker'"
echo "if path not in sys.path:"
echo "    sys.path.append(path)"
echo ""
echo "from app import app as application"
echo ""

echo "📋 Step 5: Set Environment Variables"
echo "------------------------------------"
echo "In Web tab → Environment variables:"
echo "ALPHA_VANTAGE_API_KEY = 17WLKVB018T72SGJ"
echo "FLASK_ENV = production"
echo ""

echo "📋 Step 6: Install Dependencies"
echo "------------------------------"
echo "In Consoles tab → Bash:"
echo "cd stock-options-tracker"
echo "pip3.10 install --user -r requirements.txt"
echo ""

echo "📋 Step 7: Deploy"
echo "----------------"
echo "1. Click 'Reload' in Web tab"
echo "2. Visit: https://YOUR_USERNAME.pythonanywhere.com"
echo ""

echo "🔄 Automated Update Workflow"
echo "============================"
echo ""
echo "After setup, updating your app is simple:"
echo "1. Make changes locally"
echo "2. git add . && git commit -m 'Update message' && git push"
echo "3. PythonAnywhere automatically pulls updates (if scheduled task is set up)"
echo "4. Click 'Reload' in Web tab (or set up auto-reload)"
echo ""

echo "🔧 Advanced Automation Features"
echo "==============================="
echo ""
echo "Auto-reload on file changes:"
echo "1. Create a simple PythonAnywhere task:"
echo "   cd /home/YOUR_USERNAME/stock-options-tracker"
echo "   if [ -f /tmp/reload.txt ]; then"
echo "     rm /tmp/reload.txt"
echo "     touch /home/YOUR_USERNAME/stock-options-tracker/reload.trigger"
echo "   fi"
echo ""
echo "2. Set up a webhook endpoint in your Flask app to trigger reloads"
echo ""

echo "✅ Benefits of This Setup:"
echo "- Automatic deployment from Git"
echo "- Version control and rollback capability"
echo "- Easy updates with git push"
echo "- Professional development workflow"
echo "- Cloud backup of your code"
echo "- Multiple automation options for different tiers"
echo ""
echo "🎯 Your Repository: https://github.com/PrometheusPrograms/stock-options-tracker"
