#!/bin/bash

# Stock Options Tracker - PythonAnywhere Deployment Script
# This script helps you deploy to PythonAnywhere

echo "🚀 Stock Options Tracker - PythonAnywhere Deployment"
echo "===================================================="
echo ""

echo "📋 Prerequisites:"
echo "1. PythonAnywhere account (sign up at pythonanywhere.com)"
echo "2. Your GitHub repository URL"
echo "3. Alpha Vantage API key (optional)"
echo ""

echo "🔧 Step-by-Step Instructions:"
echo ""
echo "STEP 1: Upload Code"
echo "------------------"
echo "Option A - From Git (Recommended):"
echo "1. Go to Files tab in PythonAnywhere"
echo "2. Click 'Clone from Git'"
echo "3. Enter: https://github.com/YOUR_USERNAME/stock-options-tracker.git"
echo "4. Click 'Clone'"
echo ""
echo "Option B - Manual Upload:"
echo "1. Go to Files tab"
echo "2. Upload all files from your local project"
echo ""

echo "STEP 2: Install Dependencies"
echo "----------------------------"
echo "1. Go to Consoles tab"
echo "2. Click 'Bash'"
echo "3. Run these commands:"
echo "   cd stock-options-tracker"
echo "   pip3.10 install --user -r requirements-pythonanywhere.txt"
echo ""

echo "STEP 3: Create Web App"
echo "---------------------"
echo "1. Go to Web tab"
echo "2. Click 'Add a new web app'"
echo "3. Choose 'Flask'"
echo "4. Set Python version to 3.10"
echo "5. Set source code directory to: /home/YOUR_USERNAME/stock-options-tracker"
echo "6. Set WSGI file to: wsgi.py"
echo ""

echo "STEP 4: Configure Environment Variables"
echo "--------------------------------------"
echo "1. Go to Web tab"
echo "2. Click 'Environment variables'"
echo "3. Add:"
echo "   ALPHA_VANTAGE_API_KEY = your_api_key_here"
echo "   FLASK_ENV = production"
echo ""

echo "STEP 5: Reload Web App"
echo "---------------------"
echo "1. Go to Web tab"
echo "2. Click 'Reload' button"
echo "3. Your app will be available at: https://YOUR_USERNAME.pythonanywhere.com"
echo ""

echo "🔧 Files Included for PythonAnywhere:"
echo "- wsgi.py (WSGI configuration)"
echo "- requirements-pythonanywhere.txt (dependencies)"
echo "- PYTHONANYWHERE_DEPLOYMENT.md (detailed guide)"
echo ""

echo "🚨 Troubleshooting:"
echo "- Check Error log in Web tab if issues occur"
echo "- Verify all dependencies are installed"
echo "- Ensure environment variables are set"
echo "- Check file permissions"
echo ""

echo "✅ After deployment, your app will have:"
echo "- Complete stock options tracking"
echo "- Real-time dashboard"
echo "- Cost basis calculations"
echo "- Commission tracking"
echo "- Modern responsive UI"
echo ""

echo "📞 Need help? Check PYTHONANYWHERE_DEPLOYMENT.md for detailed instructions"
