#!/bin/bash

echo "🚀 Automated PythonAnywhere Deployment Setup"
echo "============================================="
echo ""

echo "📋 Step 1: Create GitHub Repository"
echo "-----------------------------------"
echo "1. Go to https://github.com"
echo "2. Click 'New repository' (green button)"
echo "3. Repository name: stock-options-tracker"
echo "4. Description: Stock Options Trading Tracker with Cost Basis Analysis"
echo "5. Make it Public (or Private if you prefer)"
echo "6. DO NOT initialize with README (we already have files)"
echo "7. Click 'Create repository'"
echo ""

echo "📋 Step 2: Connect Local Repository to GitHub"
echo "---------------------------------------------"
echo "After creating the repository, GitHub will show you commands like:"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/stock-options-tracker.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "Replace YOUR_USERNAME with your actual GitHub username"
echo ""

echo "📋 Step 3: Push Your Code"
echo "-------------------------"
echo "Run these commands in your terminal:"
echo ""
echo "# Add the remote repository"
echo "git remote add origin https://github.com/YOUR_USERNAME/stock-options-tracker.git"
echo ""
echo "# Push your code"
echo "git push -u origin main"
echo ""

echo "📋 Step 4: Configure PythonAnywhere"
echo "------------------------------------"
echo "1. Go to PythonAnywhere Files tab"
echo "2. Click 'Clone from Git'"
echo "3. Enter: https://github.com/YOUR_USERNAME/stock-options-tracker.git"
echo "4. Click 'Clone'"
echo "5. This will create a 'stock-options-tracker' folder"
echo ""

echo "📋 Step 5: Set Up Web App"
echo "-------------------------"
echo "1. Go to Web tab"
echo "2. Click 'Add a new web app'"
echo "3. Choose Flask, Python 3.10"
echo "4. Source code directory: /home/YOUR_USERNAME/stock-options-tracker"
echo "5. WSGI file: wsgi.py"
echo ""

echo "📋 Step 6: Configure WSGI"
echo "-------------------------"
echo "In Web tab, click WSGI file and replace with:"
echo ""
echo "import sys"
echo "path = '/home/YOUR_USERNAME/stock-options-tracker'"
echo "if path not in sys.path:"
echo "    sys.path.append(path)"
echo ""
echo "from app import app as application"
echo ""

echo "📋 Step 7: Set Environment Variables"
echo "-----------------------------------"
echo "In Web tab → Environment variables:"
echo "ALPHA_VANTAGE_API_KEY = 17WLKVB018T72SGJ"
echo "FLASK_ENV = production"
echo ""

echo "📋 Step 8: Install Dependencies"
echo "-------------------------------"
echo "In Consoles tab → Bash:"
echo "cd stock-options-tracker"
echo "pip3.10 install --user -r requirements.txt"
echo ""

echo "📋 Step 9: Deploy"
echo "-----------------"
echo "1. Click 'Reload' in Web tab"
echo "2. Visit: https://YOUR_USERNAME.pythonanywhere.com"
echo ""

echo "🔄 Automated Updates"
echo "--------------------"
echo "To update your app:"
echo "1. Make changes locally"
echo "2. git add ."
echo "3. git commit -m 'Update message'"
echo "4. git push"
echo "5. In PythonAnywhere: cd stock-options-tracker && git pull"
echo "6. Click 'Reload' in Web tab"
echo ""

echo "✅ Benefits of Git Deployment:"
echo "- Version control"
echo "- Easy updates"
echo "- Backup in the cloud"
echo "- Collaboration ready"
echo "- Rollback capability"
